// Generated by CoffeeScript 1.8.0
(function() {
  var count, graph, ourBridge;

  ourBridge = window.Bridge.build();

  count = 0;

  graph = new cnnvis.Graph();

  ourBridge.onFrame = function(allPositions) {
    var finger, frame, _i, _len;
    frame = FingerUtils.toNormalizedFrame(allPositions);
    console.log('Frame: ' + JSON.stringify(frame));
    for (_i = 0, _len = frame.length; _i < _len; _i++) {
      finger = frame[_i];
      graph.add(count, finger[0]);
      graph.drawSelf(document.getElementById('graph'));
      console.log('Finger: ' + JSON.stringify(finger));
    }
    return count++;
  };

}).call(this);
